repos:
    # Enforce code style
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Enforce code style (Black)

    # Check markup files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the ref you want to point at
    hooks:
      - id: check-toml
        name: Check for valid syntax in TOML files
      - id: check-yaml
        name: Check for valid syntax in YAML files

    # Enforce import ordering
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: Enforce import ordering (isort)
