language: python

# speed up travis runs
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

# run tests and linting separately
matrix:
  include:
#    - name: "3.8 lint"
#      python: 3.8
#      env:
#        - TEST_CMD="pre-commit run --all-files"
    - name: "3.8 tests"
      python: 3.8
      env:
#        - TEST_CMD="pytest --cov=./"
        - TEST_CMD="python -c 'import compass'"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pre-commit # codecov

# command to run tests
script:
  - $TEST_CMD

#after_success:
#  - codecov

before_deploy:
#  # Install extra packages for build
#  - pip install
  # Generate sdist for PyPI and GH Releases
  - python setup sdist

deploy:
  - provider: pypi
    username: "__token__"
    password:  $PYPI_API_TOKEN
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
      distributions: bdist_wheel
      repo: the-scouts/compass-interface-core
  - provider: releases
    api_key: $GH_API_TOKEN
    file: "dist/compass-interface-core-*.tar.gz"
    skip_cleanup: true
    draft: true
    on:
      tags: true
      repo: the-scouts/compass-interface-core
