language: python

# speed up travis runs
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

# run tests and linting separately
matrix:
  include:
    - name: "3.8 lint"
      python: 3.8
      env:
        - TEST_CMD="pre-commit run --all-files"
#    - name: "3.8 tests"
#      python: 3.8
#      env:
#        - TEST_CMD="pytest --cov=./"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pre-commit # codecov

# command to run tests
script:
  - $TEST_CMD

#after_success:
#  - codecov
