services:
  backend:
    container_name: backend-cont
    ports:
      - 8888:8888
    volumes:
      - backend_vol:/sessions
    image: scouts/compass-interface-backend
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - PORT=8888
      - CI_SESSION_STORE=/sessions
    command: "compass.api.app:app"
    build:
      context: ./
      dockerfile: backend.dockerfile
      args:
        gunicorn_conf: "gunicorn_conf.py"

volumes:
  backend_vol:
