version: "3.3"
services:

  backend:
    container_name: backend-cont
    ports:
      - 8888:8888
    volumes:
      - ./compass:/app/compass
    image: scouts/compass-interface-backend
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - PORT=8888
    build:
      context: ./docker/
      dockerfile: backend.dockerfile
#      args:
#        INSTALL_DEV: ${INSTALL_DEV-false}
