compass_username = "JohnSmith"
compass_password = "Hunter2"

tenant_id = "balamory.onmicrosoft.com"
o365_domain = "balamoryscouts.org.uk"
organisation_name = "Balamory Scouts"

# options can also be specified via enviromnent variables or command-line options.
