name: 📦 Tag releases

on:
  push:
    branches: ["master"]

jobs:
  release:
    name: Tag releases
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '🔖 RLS:')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install tomli
        run: python -m pip install tomli

      - name: Run release tool
        run: python tools/prepare_release.py

  call-publish:
    name: Run publish workflow
    needs: release
    uses: the-scouts/compass-interface/.github/workflows/publish-packages.yml@master
