name: 🚀 Deploy to Azure

on:
  push:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Create requirements.txt
        # use CheeseShop version
#        run: echo compass-interface[deploy] > requirements.txt
        run: printf '%s\n' 'compass-interface' 'cryptography' 'uvicorn' 'uvloop' 'httptools' >  requirements.txt

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: compass-interface
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_2021_04 }}
