name: 🚀 Deploy to Azure

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        # use CheeseShop version
        run: |
          python -m pip install --upgrade pip
          pip install compass-interface

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: compass-interface
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v2
        with:
          name: compass-interface
          path: .

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: compass-interface
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_2021_04 }}
