name: Lint source code

on:
  pull_request:
  push:
    branches: [master]  # on all branches?

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool:
#          - flake8  # (pyflakes, pycodestyle, mccabe) + pep8-naming
          - pylint  # source linting
#          - pydocstyle  # PEP 257 compliance
#          - dodgy
#          - pyroma
#          - vulture

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ matrix.tool }}
        run:  python -m ${{ matrix.tool }}
