name: 📦 Build and publish packages

on:
  push:
    tags:
      - "v*"

jobs:
  subpackages:
    name: Build & release ${{ matrix.subpackage }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subpackage:
          - compass.core
          - compass.api
          - compass.experiments
          - compass-metapackage
    outputs:
      version: ${{ env.VERSION }}  # evaluated at the end of the job
    steps:
      - run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3
          cache: 'pip'
          cache-dependency-path: ci/requirements-build.txt

      - name: Install build dependencies
        run: python -m pip install -r ci/requirements-build.txt

      - name: Build sdist and wheel
        run: python tools/build_subpackages.py ${{ matrix.subpackage }}

      - name: Upload for GH Release
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/compass_interface*.tar.gz
            dist/compass_interface*.whl

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#          TWINE_REPOSITORY_URL: ""
        run: |
          twine check dist/*
          twine upload dist/*

      - name: (DEBUG) Upload files
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debug-build-files
          path: "*"

  gh-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: subpackages
    steps:
      - name: Get built packages
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ needs.subpackages.outputs.version }}
          body: compass-interface ${{ github.ref_name }}
          files: dist/*
          draft: true
