name: ✅ tests and coverage

on:
  pull_request:
  push:
    branches: [master]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci/requirements-test.txt

      - name: Install pytest-cov, codecov
        run: |
          pip install pytest-cov codecov

      - name: Test with pytest
        run: |          
          python -m pytest --cov=./

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1
